# Generated by Django 3.2.6 on 2021-09-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_auto_20210902_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline',
            new_name='Airport',
        ),
    ]
