# Generated by Django 3.2.6 on 2021-09-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0004_auto_20210902_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
